### ISSUE TITLE
APL2001_M02_L02_Managed_Identity_for_Projects_and_Pipelines.md - blocking issue (missing instructions)

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/implement-security-through-pipeline-using-devops#22]
### What happened?

Lab/Demo: 'Module 2: Manage identity for projects, pipelines, and agents'
Exercise : 03
Task: 02
Step: 02

Description of issue:

The text is missing any instructions on how to successfully 'install the agent' in this step, and although it refers to 'Exercise 1' (which itself point to a direct link to APL2001_M01_L01_Configure_Agents_And_Agent_Pools_for_Secure_Pipelines.md) I do not see steps that cover the process there either.

### Relevant screenshots

paste here 😉

**Comment by TesterTesterson1004** [comment]
Don't think I can reopen this issue, so I may need to repost it fresh but:  apologies that I wasn't more clear in my initial issue description:  the changes made have just edited the links **but that doesn't resolve the issue.**

The issue is that in order to proceed past this step I have to guess as to which document, and which steps within those documents, I am supposed to follow.  A student following Instructions typically shouldn't have to do that: the proper steps should be explicitly laid out for them in a specific Exercise/Task(s) section of THIS labs Instructions.

Keep in mind that a typical student is taking this course to learn about DevOps, and likely doesn't know much (or anything) about how this works....a student learning a new app/process/tech should never be made to **guess** what is the next correct step.

**Comment by lauraAlvEl** [comment]
Closed issues calling PR resolved.
