### ISSUE TITLE
APL2001_M07_L07: Missing params

### ISSUE THREAD

**Issue by bpelikan** [MicrosoftLearning/implement-security-through-pipeline-using-devops#35]
### What happened?

[Lab/Demo: APL2001_M07_L07](https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/blob/main/Instructions/Labs/APL2001_M07_L07_Configure_Pipelines_to_Securely_Use_Variables_and_Parameters.md)

Description of issue:
Missing params `${{ parameters.dotNetProjects }}` in YAML on lab page

Repro steps:
1. Go to page: https://microsoftlearning.github.io/implement-security-through-pipeline-using-devops/Instructions/Labs/APL2001_M07_L07_Configure_Pipelines_to_Securely_Use_Variables_and_Parameters.html
2. Task 2: Ensure parameter types for YAML pipelines
3. 
![image](https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/assets/24376947/f278af15-0d5b-4ab2-8fac-02649e6b3749)

**Comment by LuizMacedo** [comment]
Thanks @bpelikan!

**Comment by bpelikan** [comment]
@LuizMacedo parameters still doesn't show up correctly
![image](https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/assets/24376947/7fc894ed-d5aa-4d9f-98d3-7c211940749a)

**Comment by LuizMacedo** [comment]
I know, working on it!

**Comment by LuizMacedo** [comment]
@bpelikan its fixed now! Thanks for the heads-up and for creating the issue. The problem was the way Jekyll's Liquid (GitHub Pages) render the curly braces. Now I know :)
