### ISSUE TITLE
APL2001_M03_L03_Managed_Identity_for_Projects_and_Pipelines

### ISSUE THREAD

**Issue by Yiizo** [MicrosoftLearning/implement-security-through-pipeline-using-devops#39]
### What should we change?

Exercise 1: Import and run CI/CD Pipelines
Task 1: Import and run the CI pipeline

We are asked to Name it eshoponweb-ci and select Save. This is already created from previous modules, 

Task 2: Import and run the CD pipeline
Same issue, eshoponweb-cd-webapp-code is already createdl.

**Comment by massimobonanni** [comment]
I give my 5 cents.
If you mean **Configure a project and repository structure to support secure pipelines** as previous module, at the end of the module you can find instructions ([here](https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/blob/main/Instructions/Labs/APL2001_M01_L01_Configure_a_Project_and_Repository_Structure_to_Support_Secure_Pipelines.md#exercise-2-perform-cleanup-of-azure-and-azure-devops-resources)) to delete pipelines and repo.
I think that if you follow those instructions, you don't have the pipeline already defined in your project.
Please check if I write a right thing or not. 😄
