### ISSUE TITLE
APL2001_M01_L01:  Incorrect 'templateFile' parameter's value in '.ado/eshoponweb-secure-variables.yml'

### ISSUE THREAD

**Issue by vBardys** [MicrosoftLearning/implement-security-through-pipeline-using-devops#41]
### Contact Details

bardys@wp.pl

### What happened?

**Lab/Demo:**  Implement security through a pipeline using Azure DevOps / Configure a project and repository structure to support secure pipelines / Lab - Configure a project and repository structure to support secure pipelines

https://learn.microsoft.com/en-us/training/modules/configure-project-repository-structure-support-secure-pipelines/4-lab-configure-project-repository-structure-support-secure-pipelines

**Exercise :** Configure a project and repository structure to support secure pipelines
**Task 3:** Move the CD pipeline variables to a YAML template
**Step: 4.** Add the variables section used in the CD pipeline to the new file. The file should look like the following:

**Description of issue:** Incorrect 'templateFile' parameter's value in '.ado/eshoponweb-secure-variables.yml' 

**is:** templateFile: '.azure/bicep/webapp.bicep'
**should be?:** templateFile: 'infra/webapp.bicep'

**which results in:**

##[error]Error: Could not find any file matching the template file pattern

**in** 'Deploy to WebApp -> Deploy -> Deploy App Service Plan Bicep''

### Relevant screenshots

![obraz](https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/assets/110423153/6fa1d76f-bd3b-468a-896f-b3cbb1bb2fc4)

**Comment by LuizMacedo** [comment]
Fixed by #40. Thanks!
