### ISSUE TITLE
APL2001_M01_L01_Configure_a_Project_and_Repository_Structure_to_Support_Secure_Pipelines.md

### ISSUE THREAD

**Issue by dipankar98228** [MicrosoftLearning/implement-security-through-pipeline-using-devops#42]
### Contact Details

dipankar98228@gmail.com

### What should we change?

Exercise 2: Configure a pipeline and template structure to support secure pipelines

### Relevant screenshots

paste here 😉
<img width="1108" alt="Screenshot 2024-03-03 at 10 41 48 AM" src="https://github.com/MicrosoftLearning/implement-security-through-pipeline-using-devops/assets/23465039/59d417eb-3a1e-48f8-9419-ea65800c64b6">

**Comment by LuizMacedo** [comment]
Fixed by #40. Thanks!
