### ISSUE TITLE
M01-LAB03: Screenshot shows debug logs which need to be enabled

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#43]
### Contact Details

mkennten@microsoft.com

### What should we change?

For exercise "Managed identity for projects and pipelines", Task 3 (Task 3: Update the CD pipeline), step 11 shows a screenshot of the pipeline run logs with debug logging enabled. This is not the default and therefore we cannot see the highlighted lines to check if the Managed Identity was used. Step 8 could be changed to have the user enable "Enable system diagnostics".

### Relevant screenshots

![image](https://github.com/user-attachments/assets/57233d5d-199b-48e6-b96b-ad796a034b1c)

**Comment by LuizMacedo** [comment]
Good catch, @mkennten. Thanks! It will be fixed in the PR #51. Closing the issue.
