### ISSUE TITLE
M01-LAB03: Wrong link to other lab

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#44]
### What happened?

Lab: 03 - Managed identity for projects and pipelines

Description of issue:
In the "Before you start" section the link "Complete the lab..." doesn't work (404).

The links points to:
https://microsoftlearning.github.io/implement-security-through-pipeline-using-devops/Instructions/Labs/APL2001_M03_L02_Configure_Agents_And_Agent_Pools_for_Secure_Pipelines.md

It should point to:
https://microsoftlearning.github.io/implement-security-through-pipeline-using-devops/Instructions/Labs/APL2001_M02_L02_Configure_Agents_And_Agent_Pools_for_Secure_Pipelines.html

### Relevant screenshots

-

**Comment by LuizMacedo** [comment]
Good catch, @mkennten. Thanks! It will be fixed in the PR #51. Closing the issue.
