### ISSUE TITLE
M01-LAB04: Approvals need to have "Allow approvers to approve their own runs" checked

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#46]
### Contact Details

mkennten@microsoft.com

### What happened?

Lab: Configure and validate permissions
Exercise : 02
Task: 01
Step: 08

Description of issue:
The instructions don't mention and the screenshot is not showing that the checkbox "Allow approvers to approve their own runs" need to be checked. Just adding my username doesn't work, I won't be able to approve the job.

The screenshot should be updated, and the instruction should explicitly say that this checkbox needs to be checked.

I tested this with the checkbox for Test and without for Production.

### Relevant screenshots

![image](https://github.com/user-attachments/assets/9e5057df-da9d-4def-aee1-57f6bbcaddac)

![image](https://github.com/user-attachments/assets/f1886bce-a433-4d32-9511-5eebe492441a)

![image](https://github.com/user-attachments/assets/20ff64d8-2ef6-4690-9a87-2527e43fdb27)

**Comment by LuizMacedo** [comment]
Good catch, @mkennten. Thanks! It will be fixed in the PR #51. Closing the issue.
