### ISSUE TITLE
M02-LAB02: .NET SDK 8 missing

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#49]
### Contact Details

mkennten@microsoft.com

### What happened?

Lab: Configure agents and agent pools for secure pipelines
Exercise: 01
Task: 05 (Configure the agent)
Step: 07

Description of issue:
Microsoft .NET 7.0 SDK is installed but the eShopOnWeb solution has been updated to .NET 8 and we should have that SDK installed on the custom VM to be able to change the CI pipeline to use the self-hosted pool as well.

Note: there is no explicit mention of changing the CI pipeline to the self-hosted pool, but why then install the SDK altogether? Either don't install the SDK and the correct one.

Successfully tested with version 8.0.401.

Repro steps:
1. Complete Exercise 1 and 2 of this lab.
2. Change the eshoponweb-ci pipeline to use the self-hosted pool and run it.
3. Step Restore will fail.

### Relevant screenshots

![image](https://github.com/user-attachments/assets/e4bf2015-3368-46ec-8667-772b0615e497)

![image](https://github.com/user-attachments/assets/0c7e7c0e-b602-4479-a84e-b7b04b500523)

**Comment by LuizMacedo** [comment]
Thanks @mkennten. We will have .NET 8 SDK in the new environment for all 3 courses (AZ-2001, 2008 and 400). I'm still testing the environment to share with you. Hopefully, I'll give you access this week.
