### ISSUE TITLE
M02-LAB02: Exercise 4 should be exercise 3

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/implement-security-through-pipeline-using-devops#50]
### Contact Details

mkennten@microsoft.com

### What happened?

Lab: Configure agents and agent pools for secure pipelines
Exercise: 04

Description of issue:
This lab has exercises 1,2, and 4. 4 should be changed to 3.

**Comment by LuizMacedo** [comment]
Good catch, @mkennten. Thanks! It will be fixed in the PR #51. Closing the issue.
