### ISSUE TITLE
M00-LAB00: Getting Errror Your Azure Pass Subscription is expired for this promo code 

### ISSUE THREAD

**Issue by Yasin2018** [MicrosoftLearning/implement-security-through-pipeline-using-devops#52]
### Contact Details

yasinmca2003@gmail.com

### What happened?

Hi , I am trying to complete the Lab exercise as part of the course and i could not access the lab with same promo code  it says "Your Azure Pass Subscription is expired for this promo code " kindly advise.

**Comment by LuizMacedo** [comment]
@Yasin2018 please, contact your instructor or lab provider to request the Azure Pass. Thanks.
